services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wordpress_network
    healthcheck: # Добавляем healthcheck для MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "-u", "root", "-pwordpress_root_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always # Добавляем автоматический перезапуск

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp_theme/1expertnsk:/var/www/html/wp-content/themes/1expertnsk
    depends_on:
      db:
        condition: service_healthy # Зависимость от healthcheck
    networks:
      - wordpress_network
    restart: always # Добавляем автоматический перезапуск

volumes:
  db_data:

networks:
  wordpress_network: